<?php
if (!defined('IN_ADMINCP')) exit('Access Denied'); require_once dirname(__DIR__).'/lib/config.php';
if (submitcheck('imagesettingssubmit')) {
    stk_project_set_config('max_images',(string)max(1,min(12,(int)($_POST['max_images']??9)))); stk_project_set_config('max_image_bytes',(string)max(1048576,min(52428800,(int)($_POST['max_image_bytes']??10485760)))); stk_project_set_config('image_long_edge',(string)max(640,min(4096,(int)($_POST['image_long_edge']??1920)))); stk_project_set_config('jpeg_quality',(string)max(50,min(95,(int)($_POST['jpeg_quality']??82))));
    $types=array_values(array_intersect(array_map('trim',explode(',',(string)($_POST['allowed_image_types']??''))),['image/jpeg','image/png','image/webp'])); if(!$types)cpmsg('至少保留一种图片 MIME','', 'error'); stk_project_set_config('allowed_image_types',implode(',',$types));
    $staticBaseUrl=rtrim(trim((string)($_POST['static_base_url']??'')),'/'); if($staticBaseUrl!=='' && (!filter_var($staticBaseUrl,FILTER_VALIDATE_URL) || strtolower((string)parse_url($staticBaseUrl,PHP_URL_SCHEME))!=='https'))cpmsg('静态资源域名必须是 HTTPS URL','','error'); stk_project_set_config('static_base_url',$staticBaseUrl);
    stk_project_admin_audit('images','config_update'); cpmsg('图片规则已保存','action=plugins&operation=config&do='.$pluginid.'&identifier=stk_project&pmod=image_settings','succeed');
}
showformheader('plugins&operation=config&do='.$pluginid.'&identifier=stk_project&pmod=image_settings'); showtableheader('图片与存储设置'); showsetting('最大图片数','max_images',stk_project_config('max_images','9'),'text'); showsetting('单图最大字节','max_image_bytes',stk_project_config('max_image_bytes','10485760'),'text'); showsetting('压缩最长边像素','image_long_edge',stk_project_config('image_long_edge','1920'),'text'); showsetting('JPEG 质量','jpeg_quality',stk_project_config('jpeg_quality','82'),'text'); showsetting('允许 MIME（逗号分隔）','allowed_image_types',stk_project_config('allowed_image_types','image/jpeg,image/png,image/webp'),'text'); showsetting('静态资源 HTTPS 根地址','static_base_url',stk_project_config('static_base_url',''),'text','',0,'留空时使用 Discuz 主站；配置后新上传图片和临时资源 URL 使用该域名。'); showsubmit('imagesettingssubmit','保存'); showtablefooter(); showformfooter();
$temporary=(int)DB::result_first('SELECT COUNT(*) FROM %t WHERE status=%s',['stk_project_upload','temporary']);$bound=(int)DB::result_first('SELECT COUNT(*) FROM %t WHERE status=%s',['stk_project_upload','bound']);showtableheader('资产状态');showtablerow('',[],['临时资产',(string)$temporary]);showtablerow('',[],['已绑定资产',(string)$bound]);showtablefooter();
