<?php
if (!defined('IN_DISCUZ')) exit('Access Denied');
$sql=<<<SQL
CREATE TABLE IF NOT EXISTS `pre_stk_project_config` (`config_key` varchar(64) NOT NULL,`config_value` text NOT NULL,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`config_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_category` (`category_id` varchar(32) NOT NULL,`name` varchar(64) NOT NULL,`sort_order` int NOT NULL DEFAULT 0,`enabled` tinyint unsigned NOT NULL DEFAULT 1,PRIMARY KEY (`category_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project` (`project_id` bigint unsigned NOT NULL AUTO_INCREMENT,`publisher_uid` int unsigned NOT NULL,`title` varchar(120) NOT NULL,`summary` text NOT NULL,`category_id` varchar(32) NOT NULL,`cover_url` varchar(500) NOT NULL DEFAULT '',`publisher_name` varchar(64) NOT NULL,`member_label` varchar(32) NOT NULL DEFAULT '普通用户',`contact_name` varchar(64) NOT NULL DEFAULT '',`contacts_json` text NOT NULL,`status` varchar(16) NOT NULL DEFAULT 'pending',`rejection_reason` varchar(500) NOT NULL DEFAULT '',`view_count` int unsigned NOT NULL DEFAULT 0,`row_version` int unsigned NOT NULL DEFAULT 1,`published_at` int unsigned NOT NULL DEFAULT 0,`created_at` int unsigned NOT NULL DEFAULT 0,`updated_at` int unsigned NOT NULL DEFAULT 0,`deleted_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`project_id`),KEY `idx_owner_status` (`publisher_uid`,`status`,`project_id`),KEY `idx_status_id` (`status`,`project_id`),KEY `idx_category_status` (`category_id`,`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_image` (`image_id` bigint unsigned NOT NULL AUTO_INCREMENT,`project_id` bigint unsigned NOT NULL,`asset_id` bigint unsigned NOT NULL DEFAULT 0,`image_url` varchar(500) NOT NULL,`alt_text` varchar(120) NOT NULL DEFAULT '',`sort_order` int NOT NULL DEFAULT 0,`mime_type` varchar(64) NOT NULL DEFAULT '',`size_bytes` bigint unsigned NOT NULL DEFAULT 0,`storage_key` varchar(500) NOT NULL DEFAULT '',PRIMARY KEY (`image_id`),KEY `idx_project_sort` (`project_id`,`sort_order`),KEY `idx_asset_id` (`asset_id`),KEY `idx_storage_key` (`storage_key`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_upload` (`asset_id` bigint unsigned NOT NULL AUTO_INCREMENT,`owner_uid` int unsigned NOT NULL,`project_id` bigint unsigned NOT NULL DEFAULT 0,`storage_key` varchar(500) NOT NULL,`mime_type` varchar(64) NOT NULL,`size_bytes` bigint unsigned NOT NULL DEFAULT 0,`status` varchar(16) NOT NULL DEFAULT 'temporary',`expires_at` int unsigned NOT NULL DEFAULT 0,`created_at` int unsigned NOT NULL DEFAULT 0,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`asset_id`),UNIQUE KEY `uk_storage_key` (`storage_key`(191)),KEY `idx_owner_status` (`owner_uid`,`status`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_view_daily` (`project_id` bigint unsigned NOT NULL,`view_date` date NOT NULL,`viewer_hash` char(64) NOT NULL,`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`project_id`,`view_date`,`viewer_hash`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_audit` (`audit_id` bigint unsigned NOT NULL AUTO_INCREMENT,`project_id` bigint unsigned NOT NULL,`operator_uid` int unsigned NOT NULL DEFAULT 0,`action` varchar(32) NOT NULL,`from_status` varchar(16) NOT NULL DEFAULT '',`to_status` varchar(16) NOT NULL DEFAULT '',`reason` varchar(500) NOT NULL DEFAULT '',`payload_json` text NOT NULL,`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`audit_id`),KEY `idx_project_created` (`project_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_audit_log` (`audit_id` bigint unsigned NOT NULL AUTO_INCREMENT,`project_id` bigint unsigned NOT NULL,`operator_uid` int unsigned NOT NULL DEFAULT 0,`action` varchar(32) NOT NULL,`from_status` varchar(16) NOT NULL DEFAULT '',`to_status` varchar(16) NOT NULL DEFAULT '',`reason` varchar(500) NOT NULL DEFAULT '',`payload_json` text NOT NULL,`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`audit_id`),KEY `idx_project_created` (`project_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_member_status` (`uid` int unsigned NOT NULL,`status` varchar(16) NOT NULL DEFAULT 'inactive',`member_label` varchar(32) NOT NULL DEFAULT '普通用户',`level` varchar(16) NOT NULL DEFAULT 'L1',`starts_at` int unsigned NOT NULL DEFAULT 0,`expires_at` int unsigned NOT NULL DEFAULT 0,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`uid`),KEY `idx_status_expiry` (`status`,`expires_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_wallet_account` (`uid` int unsigned NOT NULL,`commission_amount` decimal(12,2) NOT NULL DEFAULT 0,`task_amount` decimal(12,2) NOT NULL DEFAULT 0,`task_points` int unsigned NOT NULL DEFAULT 0,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`uid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_prop_catalog` (`prop_id` varchar(32) NOT NULL,`name` varchar(64) NOT NULL,`description` varchar(255) NOT NULL DEFAULT '',`icon_url` varchar(500) NOT NULL DEFAULT '',`sort_order` int NOT NULL DEFAULT 0,`enabled` tinyint unsigned NOT NULL DEFAULT 1,PRIMARY KEY (`prop_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_release` (`release_id` bigint unsigned NOT NULL AUTO_INCREMENT,`version_name` varchar(32) NOT NULL,`version_code` int unsigned NOT NULL,`minimum_version_name` varchar(32) NOT NULL DEFAULT '1.3.0-beta.1',`minimum_version_code` int unsigned NOT NULL DEFAULT 0,`apk_url` varchar(500) NOT NULL,`apk_sha256` char(64) NOT NULL,`apk_size_bytes` bigint unsigned NOT NULL DEFAULT 0,`mandatory` tinyint unsigned NOT NULL DEFAULT 0,`notes` text NOT NULL,`status` varchar(16) NOT NULL DEFAULT 'draft',`enabled` tinyint unsigned NOT NULL DEFAULT 0,`published_at` int unsigned NOT NULL DEFAULT 0,`created_at` int unsigned NOT NULL DEFAULT 0,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`release_id`),UNIQUE KEY `uk_version_code` (`version_code`),KEY `idx_status_version` (`status`,`version_code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_admin_audit` (`audit_id` bigint unsigned NOT NULL AUTO_INCREMENT,`operator_uid` int unsigned NOT NULL DEFAULT 0,`section` varchar(32) NOT NULL,`action` varchar(32) NOT NULL,`payload_json` text NOT NULL,`ip` varchar(64) NOT NULL DEFAULT '',`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`audit_id`),KEY `idx_section_created` (`section`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_request_guard` (`request_hash` char(64) NOT NULL,`uid` int unsigned NOT NULL,`action` varchar(128) NOT NULL,`response_json` mediumtext NULL,`response_status` smallint unsigned NOT NULL DEFAULT 200,`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`request_hash`),KEY `idx_uid_action_created` (`uid`,`action`(64),`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_app_config` (`config_key` varchar(64) NOT NULL,`config_value` text NOT NULL,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`config_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO `pre_stk_project_config` (`config_key`,`config_value`,`updated_at`) VALUES ('browse_enabled','1',UNIX_TIMESTAMP()),('page_size','20',UNIX_TIMESTAMP()),('default_sort','latest',UNIX_TIMESTAMP()),('categories_enabled','1',UNIX_TIMESTAMP()),('show_publisher_avatar','1',UNIX_TIMESTAMP()),('show_member_badge','1',UNIX_TIMESTAMP()),('show_view_count','1',UNIX_TIMESTAMP()),('show_publish_time','1',UNIX_TIMESTAMP()),('empty_text','暂无项目',UNIX_TIMESTAMP()),('default_cover_url','',UNIX_TIMESTAMP()),('external_url_allowlist','stk.zz-yihao.com',UNIX_TIMESTAMP()),('contact_types','phone,wechat,qq,url',UNIX_TIMESTAMP()),('publish_enabled','1',UNIX_TIMESTAMP()),('review_mode','manual',UNIX_TIMESTAMP()),('title_min','4',UNIX_TIMESTAMP()),('title_max','60',UNIX_TIMESTAMP()),('summary_min','10',UNIX_TIMESTAMP()),('summary_max','1000',UNIX_TIMESTAMP()),('max_images','9',UNIX_TIMESTAMP()),('max_image_bytes','10485760',UNIX_TIMESTAMP()),('allowed_image_types','image/jpeg,image/png,image/webp',UNIX_TIMESTAMP()),('image_long_edge','1920',UNIX_TIMESTAMP()),('jpeg_quality','82',UNIX_TIMESTAMP()),('static_base_url','',UNIX_TIMESTAMP()),('daily_limit','10',UNIX_TIMESTAMP()),('pending_limit','5',UNIX_TIMESTAMP()),('edit_requires_review','1',UNIX_TIMESTAMP()),('user_can_offline','1',UNIX_TIMESTAMP()),('user_can_delete','1',UNIX_TIMESTAMP()),('maintenance_enabled','0',UNIX_TIMESTAMP()),('maintenance_message','系统维护中，请稍后再试。',UNIX_TIMESTAMP()),('maintenance_resume_at','',UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE config_key=VALUES(config_key);
INSERT INTO `pre_stk_app_config` (`config_key`,`config_value`,`updated_at`) SELECT `config_key`,`config_value`,`updated_at` FROM `pre_stk_project_config` ON DUPLICATE KEY UPDATE `config_value`=VALUES(`config_value`),`updated_at`=VALUES(`updated_at`);
INSERT INTO `pre_stk_project_config` (`config_key`,`config_value`,`updated_at`) VALUES ('app_links_host','stk.zz-yihao.com',UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE `config_key`=VALUES(`config_key`);
INSERT INTO `pre_stk_app_config` (`config_key`,`config_value`,`updated_at`) VALUES ('app_links_host','stk.zz-yihao.com',UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE `config_key`=VALUES(`config_key`);
INSERT INTO `pre_stk_project_config` (`config_key`,`config_value`,`updated_at`) VALUES ('schema_version','14001',UNIX_TIMESTAMP()),('show_wallets','1',UNIX_TIMESTAMP()),('commission_label','佣金账户',UNIX_TIMESTAMP()),('task_label','任务账户',UNIX_TIMESTAMP()),('show_member_card','1',UNIX_TIMESTAMP()),('member_title','商推客会员',UNIX_TIMESTAMP()),('member_benefit_discount','消费 5 折',UNIX_TIMESTAMP()),('member_benefit_rebate','消费返佣 40%',UNIX_TIMESTAMP()),('member_open_button_text','立即开通',UNIX_TIMESTAMP()),('show_props_center','1',UNIX_TIMESTAMP()),('profile_bio','',UNIX_TIMESTAMP()),('placeholder_message','功能筹备中',UNIX_TIMESTAMP()),('support_type','wechat',UNIX_TIMESTAMP()),('support_label','在线客服',UNIX_TIMESTAMP()),('support_value','',UNIX_TIMESTAMP()),('support_hours','工作日 09:00-18:00',UNIX_TIMESTAMP()),('support_copy_enabled','1',UNIX_TIMESTAMP()),('support_url_allowlist','stk.zz-yihao.com',UNIX_TIMESTAMP()),('release.current_version','1.4.0-beta.1',UNIX_TIMESTAMP()),('release.minimum_version','1.3.0-beta.1',UNIX_TIMESTAMP()),('release.force_update','0',UNIX_TIMESTAMP()),('release.download_url','https://stk-download.zz-yihao.com/app/STK-1.4.0-beta.1.apk',UNIX_TIMESTAMP()),('release.apk_sha256','',UNIX_TIMESTAMP()),('release.notes','',UNIX_TIMESTAMP()),('release.download_hosts','stk-download.zz-yihao.com,stk.zz-yihao.com',UNIX_TIMESTAMP()),('maintenance.enabled','0',UNIX_TIMESTAMP()),('maintenance.message','系统维护中，请稍后再试。',UNIX_TIMESTAMP()),('maintenance.expected_end','',UNIX_TIMESTAMP()),('app_links.host','stk.zz-yihao.com',UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE `config_key`=VALUES(`config_key`);
INSERT INTO `pre_stk_app_config` (`config_key`,`config_value`,`updated_at`) SELECT `config_key`,`config_value`,`updated_at` FROM `pre_stk_project_config` ON DUPLICATE KEY UPDATE `config_value`=VALUES(`config_value`),`updated_at`=VALUES(`updated_at`);
INSERT IGNORE INTO `pre_stk_member_status` (`uid`,`status`,`member_label`,`level`,`starts_at`,`expires_at`,`updated_at`) SELECT `uid`,'inactive','普通用户','L1',0,0,UNIX_TIMESTAMP() FROM `pre_common_member`;
INSERT IGNORE INTO `pre_stk_wallet_account` (`uid`,`commission_amount`,`task_amount`,`task_points`,`updated_at`) SELECT `uid`,0,0,0,UNIX_TIMESTAMP() FROM `pre_common_member`;
INSERT INTO `pre_stk_project_category` (`category_id`,`name`,`sort_order`,`enabled`) VALUES ('retail','零售',1,1),('service','服务',2,1),('technology','科技',3,1) ON DUPLICATE KEY UPDATE name=VALUES(name),sort_order=VALUES(sort_order);
INSERT INTO `pre_stk_prop_catalog` (`prop_id`,`name`,`description`,`sort_order`,`enabled`) VALUES ('refresh','刷新卡','刷新项目展示时间',1,1),('super_headline','超级头条','超级头条展示道具',2,1),('headline','头条','头条展示道具',3,1),('color','变色卡','项目标题变色展示',4,1) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),sort_order=VALUES(sort_order);
SQL; runquery($sql); $finish=true;
