<?php
if (!defined('IN_DISCUZ')) exit('Access Denied');
require_once __DIR__ . '/lib/config.php';
$sql = <<<SQL
CREATE TABLE IF NOT EXISTS `pre_stk_project_upload` (`asset_id` bigint unsigned NOT NULL AUTO_INCREMENT,`owner_uid` int unsigned NOT NULL,`project_id` bigint unsigned NOT NULL DEFAULT 0,`storage_key` varchar(500) NOT NULL,`mime_type` varchar(64) NOT NULL,`size_bytes` bigint unsigned NOT NULL DEFAULT 0,`status` varchar(16) NOT NULL DEFAULT 'temporary',`expires_at` int unsigned NOT NULL DEFAULT 0,`created_at` int unsigned NOT NULL DEFAULT 0,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`asset_id`),UNIQUE KEY `uk_storage_key` (`storage_key`(191)),KEY `idx_owner_status` (`owner_uid`,`status`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_prop_catalog` (`prop_id` varchar(32) NOT NULL,`name` varchar(64) NOT NULL,`description` varchar(255) NOT NULL DEFAULT '',`icon_url` varchar(500) NOT NULL DEFAULT '',`sort_order` int NOT NULL DEFAULT 0,`enabled` tinyint unsigned NOT NULL DEFAULT 1,PRIMARY KEY (`prop_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_release` (`release_id` bigint unsigned NOT NULL AUTO_INCREMENT,`version_name` varchar(32) NOT NULL,`version_code` int unsigned NOT NULL,`minimum_version_code` int unsigned NOT NULL DEFAULT 0,`apk_url` varchar(500) NOT NULL,`apk_sha256` char(64) NOT NULL,`mandatory` tinyint unsigned NOT NULL DEFAULT 0,`notes` text NOT NULL,`enabled` tinyint unsigned NOT NULL DEFAULT 1,`created_at` int unsigned NOT NULL DEFAULT 0,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`release_id`),UNIQUE KEY `uk_version_code` (`version_code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_admin_audit` (`audit_id` bigint unsigned NOT NULL AUTO_INCREMENT,`operator_uid` int unsigned NOT NULL DEFAULT 0,`section` varchar(32) NOT NULL,`action` varchar(32) NOT NULL,`payload_json` text NOT NULL,`ip` varchar(64) NOT NULL DEFAULT '',`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`audit_id`),KEY `idx_section_created` (`section`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_audit_log` (`audit_id` bigint unsigned NOT NULL AUTO_INCREMENT,`project_id` bigint unsigned NOT NULL,`operator_uid` int unsigned NOT NULL DEFAULT 0,`action` varchar(32) NOT NULL,`from_status` varchar(16) NOT NULL DEFAULT '',`to_status` varchar(16) NOT NULL DEFAULT '',`reason` varchar(500) NOT NULL DEFAULT '',`payload_json` text NOT NULL,`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`audit_id`),KEY `idx_project_created` (`project_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_app_config` (`config_key` varchar(64) NOT NULL,`config_value` text NOT NULL,`updated_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`config_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `pre_stk_project_request_guard` (`request_hash` char(64) NOT NULL,`uid` int unsigned NOT NULL,`action` varchar(128) NOT NULL,`response_json` mediumtext NULL,`response_status` smallint unsigned NOT NULL DEFAULT 200,`created_at` int unsigned NOT NULL DEFAULT 0,PRIMARY KEY (`request_hash`),KEY `idx_uid_action_created` (`uid`,`action`(64),`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
SQL;
runquery($sql);
$rowVersionColumn=DB::fetch_first('SHOW COLUMNS FROM %t LIKE %s',['stk_project','row_version']);
if(!$rowVersionColumn)DB::query("ALTER TABLE %t ADD `row_version` int unsigned NOT NULL DEFAULT 1 AFTER `view_count`",['stk_project']);
$contactNameColumn=DB::fetch_first('SHOW COLUMNS FROM %t LIKE %s',['stk_project','contact_name']);
if(!$contactNameColumn)DB::query("ALTER TABLE %t ADD `contact_name` varchar(64) NOT NULL DEFAULT '' AFTER `member_label`",['stk_project']);
$assetColumn=DB::fetch_first('SHOW COLUMNS FROM %t LIKE %s',['stk_project_image','asset_id']);
if(!$assetColumn)DB::query("ALTER TABLE %t ADD `asset_id` bigint unsigned NOT NULL DEFAULT 0 AFTER `project_id`, ADD KEY `idx_asset_id` (`asset_id`)",['stk_project_image']);
DB::query('UPDATE %t i INNER JOIN %t u ON BINARY u.storage_key=BINARY i.storage_key SET i.asset_id=u.asset_id WHERE i.asset_id=0', ['stk_project_image','stk_project_upload']);
foreach ([
    'browse_enabled'=>'1','page_size'=>'20','default_sort'=>'latest','categories_enabled'=>'1','show_publisher_avatar'=>'1','show_member_badge'=>'1','show_view_count'=>'1','show_publish_time'=>'1','empty_text'=>'暂无项目','default_cover_url'=>'','external_url_allowlist'=>'stk.zz-yihao.com','contact_types'=>'phone,wechat,qq,url',
    'publish_enabled'=>'1','review_mode'=>'manual','title_min'=>'4','title_max'=>'60','summary_min'=>'10','summary_max'=>'1000','max_images'=>'9','max_image_bytes'=>'10485760','allowed_image_types'=>'image/jpeg,image/png,image/webp','daily_limit'=>'10','pending_limit'=>'5','edit_requires_review'=>'1','user_can_offline'=>'1','user_can_delete'=>'1',
    'image_long_edge'=>'1920','jpeg_quality'=>'82','static_base_url'=>'','maintenance_enabled'=>'0','maintenance_message'=>'系统维护中，请稍后再试。','maintenance_resume_at'=>''
] as $key=>$value) if (stk_project_config($key,'')==='') stk_project_set_config($key,$value);
if (stk_project_config('app_links_host', '') === '') stk_project_set_config('app_links_host', 'stk.zz-yihao.com');
DB::query("INSERT INTO %t (prop_id,name,description,sort_order,enabled) VALUES ('refresh','刷新卡','刷新项目展示时间',1,1),('super_headline','超级头条','超级头条展示道具',2,1),('headline','头条','头条展示道具',3,1),('color','变色卡','项目标题变色展示',4,1) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),sort_order=VALUES(sort_order)", ['stk_prop_catalog']);
DB::query("INSERT IGNORE INTO %t (owner_uid,project_id,storage_key,mime_type,size_bytes,status,expires_at,created_at,updated_at) SELECT p.publisher_uid,i.project_id,i.storage_key,i.mime_type,i.size_bytes,'bound',0,p.created_at,p.updated_at FROM %t i INNER JOIN %t p ON p.project_id=i.project_id WHERE i.storage_key<>''", ['stk_project_upload','stk_project_image','stk_project']);
DB::query('UPDATE %t SET status=%s WHERE status=%s', ['stk_project', 'offline', 'unpublished']);
DB::query('INSERT INTO %t (config_key,config_value,updated_at) SELECT config_key,config_value,updated_at FROM %t ON DUPLICATE KEY UPDATE config_value=VALUES(config_value),updated_at=VALUES(updated_at)', ['stk_app_config', 'stk_project_config']);
DB::query('INSERT INTO %t (audit_id,project_id,operator_uid,action,from_status,to_status,reason,payload_json,created_at) SELECT audit_id,project_id,operator_uid,action,from_status,to_status,reason,payload_json,created_at FROM %t ON DUPLICATE KEY UPDATE action=VALUES(action),to_status=VALUES(to_status),reason=VALUES(reason),payload_json=VALUES(payload_json)', ['stk_project_audit_log', 'stk_project_audit']);
DB::query('DELETE FROM %t WHERE created_at<%d', ['stk_project_request_guard', TIMESTAMP - 86400]);
$responseColumn=DB::fetch_first('SHOW COLUMNS FROM %t LIKE %s',['stk_project_request_guard','response_json']);
if(!$responseColumn)DB::query("ALTER TABLE %t ADD `response_json` mediumtext NULL AFTER `action`, ADD `response_status` smallint unsigned NOT NULL DEFAULT 200 AFTER `response_json`",['stk_project_request_guard']);
$finish=true;
